trigger:
- main

pool:
  name: MySelfHostedAgentPool

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore
  displayName: 'Restore NuGet Packages'

- script: dotnet build --configuration Release
  displayName: 'Build Solution'

- script: dotnet test --configuration Release
  displayName: 'Run Tests'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Artifacts'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringExtensions.csproj'
    configuration: 'Release'
    arguments: '--output $(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  displayName: 'Push NuGet Package to Azure Artifacts'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'sshield9/StringExtensionsFeed'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'drop'
